### ISSUE TITLE
mapping error

### ISSUE THREAD

**Issue by rosscdh** [explorium-ai/kube-auto-puller#6]
### What happened?

Great looking app! like the use of 3rd parties 

Small issue when trying to install, may be 3rd party charts but not entirely sure dont seem to see the labels in question

```
Error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 11: mapping key "labels" already defined at line 6
  line 30: mapping key "labels" already defined at line 26
```

### How can we reproduce this?

```
kustomize build --enable-helm path/to/folder/with/below/files
```

```
cat <<EOF > kustomization.yaml
generators:
  - ./generator.yaml
EOF

cat <<EOF > generator.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: kube-auto-puller
name: kube-auto-puller
repo: https://explorium-ai.github.io/kube-auto-puller/
version: 1.1.2
releaseName: pa
namespace: default
IncludeCRDs: true
# valuesFile: values.yaml
valuesInline:
  global:
    # -- Defines the secrets which will be used to pull images into nodes and cache them
    imageCachePullSecrets:
    - dockerhub-pull
  
    # -- # List of images to exclude when creating image caches. works with Regex
    exclude:
      - ".*kube-proxy.*"
  
    # --  # List of images to include when creating image caches. works with Regex.
    include:
      - ".*"

    cacheAllOnDeploy:
      # -- On Chart install, automatically create all caches for all images in the cluster (respecting excluded list)
      enabled: true
EOF
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

its just using the helm chart inflator which issues a helm command to template output the chart.
